### ISSUE TITLE
Fix gamepad examples

### ISSUE THREAD

**Issue by dhalbert** [adafruit/Adafruit_CircuitPython_HID#71]
`gamepad.py` is no longer in the base library, because the gamepad device was removed from CircuitPython 7.0.0.

- Rename `examples/gamepad.py` to `examples/hid_gamepad.py` or similar, because `gamepad.py` overlaps with the `gamepad` built-in module.
- Fix or remove the gamepad-based examples.
- Add documentation about how to add a gamepad device to CircuitPython 7.0.0, or refer to a guide.

**Comment by dhalbert** [comment]
There's now a gamepad example in https://learn.adafruit.com/customizing-usb-devices-in-circuitpython/hid-devices#custom-hid-devices-3096614-9.

**Comment by dhalbert** [comment]
I think we should rename `examples/gamepad.py` to `examples/hid_gamepad.py`, or just discard it. The class name could stay the same.

I don't know whether we should just remove the other gamepad examples, or change them to use `hid_gamepad`. It seems odd to just discard the code, but they are kind of ancillary if there's no more `gamepad.py` in the library.

**Comment by FoamyGuy** [comment]
I'm in favor of keeping them instead of discarding even though `gamepad.py` is not a part of the library itself. I think it would be a 
shame to get rid of it entirely, and I think this is the library that it is most closely related to so it seems like a logical place for that folks looking for something like that would be checking. 

I'll make a PR with those changes.
