### ISSUE TITLE
Chromebook support

### ISSUE THREAD

**Issue by pikachub2005** [adafruit/Adafruit_CircuitPython_HID#91]
need keycodes for special chromebook keys
![61ra+DW9ZzL _AC_SL1500_](https://user-images.githubusercontent.com/74213212/147841654-ef5eb6e0-bcc9-48da-9747-91e4d66ebc90.jpg)

**Comment by dhalbert** [comment]
We don't know what those keycodes are, but we can guess. Some may correspond to existing `ConsumerControl` keycodes.

The `evtest` program can be used under Linux to find out what is sent by various keys. I don't know whether this would work in Linux mode on a Chromebook.

Keycodes are just integers. You can always send an integer instead of a named keycode.

**Comment by pikachub2005** [comment]
Ok

**Comment by dhalbert** [comment]
Closing for now.
